on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out application code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build Docker image
      run: docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) -t microvisor-remote-debug-image .
    - name: Build application code
      run: docker run --rm -v $(pwd)/:/home/mvisor/project/ --env BUILD_ONLY=true --name microvisor-remote-debug microvisor-remote-debug-image
